spring:
  datasource:
    url: jdbc:mysql://mysql:3306/microservicios?createDatabaseIfNotExist=true
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 7001

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 

logging:
  level:
    com.zaxxer.hikari: DEBUG

