spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: config-server
          uri: lb://CONFIG-SERVER
          predicates:
            - Path=/config/**
        - id: eureka-server
          uri: lb://EUREKA-SERVER
          predicates:
            - Path=/eureka/**
        - id: dashboard
          uri: lb://DASHBOARD
          predicates:
            - Path=/api/performance/**
          filters:
            - StripPrefix=0
        - id: mc1
          uri: lb://MC1
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        - id: mc2
          uri: lb://MC2
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 